export const TODO_ADDDED = "TODO_ADDED";
export const TODO_REMOVED = "TODO_REMOVED";
export const NEW_TODO_INPUT = "NEW_TODO_INPUT";
export const TODO_COMPLETED = "TODO_COMPLETED";
export const INCREASE  = "INCREASE";
export const TODO_FROM_API_SUCCESS  = "TODO_FROM_API_SUCCESS";

